# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    assignees: ["KonradHoeffner"]
    commit-message:
      prefix: 'ci'
      include: 'scope'
    schedule:
      interval: "daily"
