# Permalinks
permalink:        pretty

# Setup
title:            HITO
tagline:          'A Health IT Ontology'
description:      'A Health IT Ontology for systematically describing application systems and software products in health IT.'
#description:      'A Health IT Ontology for systematically describing application systems and software products in health IT. By <a href="https://imise.uni-leipzig.de/" target="_blank">IMISE</a> and <a href="https://umit.at/" target="_blank">UMIT</a>.'
url:              https://hitontology.eu
baseurl:         /
logo:

author:
  name:           'Konrad Höffner & Thomas Pause'
  url:            https://github.com/KonradHoeffner , https://github.com/ThomasPause

# Custom vars
version:          0.0.1

github:
  org:           https://github.com/hitontology

socialmedia:
  twitter: https://twitter.com/hitontology

internal:
  owncloud:  https://denethor.imise.uni-leipzig.de/index.php/apps/files?dir=/Shared/HITO/
  slack:     https://hito-project.slack.com/
  googledrive: https://drive.google.com/drive/folders/1vvBFwDhE9S1Mm3i317KjubNdLsW1iCJU
  qualitycheck: /qualitycheck/
  conductor: https://hitontology.eu/conductor
  form: https://hitontology.github.io/instancegenerator/
  database:
    admin: https://hitontology.eu/phppgadmin/
    schema: https://github.com/hitontology/database/releases/latest/download/HITOdatabaseUML.pdf

# link targets hosted externally, absolute URLs required
hito:
  ontology: https://hitontology.eu/ontology/
  search: https://hitontology.eu/search/

links:
  imise:     https://imise.uni-leipzig.de/
  umit:      https://umit.at/
  winter:    http://www.people.imise.uni-leipzig.de/alfred.winter/
  ammenwerth: https://www.umit.at/page.cfm?vpath=departments/technik/iig/
  hoeffner:  https://www.imise.uni-leipzig.de/Mitarbeiter/Konrad.Hoeffner.jsp
  jahn:      http://www.imise.uni-leipzig.de/Mitarbeiter/Franziska.Jahn.jsp
  schneider:  http://www.imise.uni-leipzig.de/Mitarbeiter/Birgit.Schneider.jsp
  ghalandari: http://www.imise.uni-leipzig.de/Mitarbeiter/Maryam.Ghalandari.jsp
  dornauer:   https://www.umit.at/page.cfm?vpath=departments/technik/iig/
  pause:      http://www.imise.uni-leipzig.de/Mitarbeiter/Thomas.Pause.jsp
