permalink:        pretty
# Setup
title:            HITO
tagline:          'A Health IT Ontology'
description:      'A Health IT Ontology for systematically describing application systems and software products in health IT. By <a href="https://imise.uni-leipzig.de/" target="_blank">IMISE</a> and <a href="https://umit.at/" target="_blank">UMIT</a>.'
url:              http://hitontology.eu
baseurl:          ''

author:
  name:           'Konrad Höffner'
  url:            https://github.com/KonradHoeffner

# Custom vars

github:
  repo:           https://github.com/hitontology

socialmedia:
  twitter: https://twitter.com/hitontology
