permalink:        pretty
# Setup
title:            HITO
tagline:          'A Health IT Ontology'
description:      'A Health IT Ontology for systematically describing application systems and software products in health IT. By <a href="https://imise.uni-leipzig.de/" target="_blank">IMISE</a> and <a href="https://umit.at/" target="_blank">UMIT</a>.'
url:              https://hitontology.eu
baseurl:          ''

author:
  name:           'Konrad Höffner & Thomas Pause'
  url:            https://github.com/KonradHoeffner , https://github.com/ThomasPause

# Custom vars

github:
  org:           https://github.com/hitontology

socialmedia:
  twitter: https://twitter.com/hitontology

internal:
  owncloud:  https://denethor.imise.uni-leipzig.de/index.php/apps/files?dir=/Shared/HITO/
  slack:     https://hito-project.slack.com/
